[http]
http_read_timeout  = "15s"
http_write_timeout = "15s"
ssl_certificate_path =""
ssl_keystore_path = ""
http_server_address = ":8080"
http_server_address_secure = ":443"

[db]
connection = "postgres://postgres:postgres@localhost/postgres?sslmode=disable"
max_idle_connections = 10
max_open_connections = 50
max_lifetime = "60s"